<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Moneris\Model;

use Moneris\Model\Base\MonerisErrors as BaseMonerisErrors;

/**
 * Class MonerisErrors
 * @package Moneris\Model
 */
class MonerisErrors extends BaseMonerisErrors
{
}
