<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Moneris\Action;

use Moneris\Action\Base\MonerisErrorsAction as  BaseMonerisErrorsAction;

/**
 * Class MonerisErrorsAction
 * @package Moneris\Action
 */
class MonerisErrorsAction extends BaseMonerisErrorsAction
{
}
