<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Moneris\Form\Type;

use Moneris\Form\Type\Base\MonerisErrorsIdType as BaseMonerisErrorsIdType;

/**
 * Class MonerisErrors
 * @package Moneris\Form
 */
class MonerisErrorsIdType extends BaseMonerisErrorsIdType
{
}
