<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Moneris\Event\Module\Base;

/**
 * Class MonerisEvents
 * @package Moneris\Event\Module\Base
 * @author TheliaStudio
 */
class MonerisEvents
{
    const MONERIS_ERRORS_CREATE = "action.moneris_errors.create";
    const MONERIS_ERRORS_UPDATE = "action.moneris_errors.update";
    const MONERIS_ERRORS_DELETE = "action.moneris_errors.delete";
}
