<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Moneris\Event\Module\Base;

/**
 * Class MonerisEvents
 * @package Moneris\Event\Module\Base
 * @author TheliaStudio
 */
class MonerisEvents
{
}
