<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Moneris\Event;

use Moneris\Event\Base\MonerisErrorsEvent as BaseMonerisErrorsEvent;

/**
 * Class MonerisErrorsEvent
 * @package Moneris\Event
 */
class MonerisErrorsEvent extends BaseMonerisErrorsEvent
{
}
