<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Moneris\Form\Base;

use Moneris\Form\MonerisErrorsCreateForm as ChildMonerisErrorsCreateForm;
use Moneris\Form\Type\MonerisErrorsIdType;

/**
 * Class MonerisErrorsForm
 * @package Moneris\Form
 * @author TheliaStudio
 */
class MonerisErrorsUpdateForm extends ChildMonerisErrorsCreateForm
{
    const FORM_NAME = "moneris_errors_update";

    public function buildForm()
    {
        parent::buildForm();

        $this->formBuilder
            ->add("id", MonerisErrorsIdType::TYPE_NAME)
        ;
    }
}
