<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Moneris\Loop;

use Moneris\Loop\Base\MonerisErrors as BaseMonerisErrorsLoop;

/**
 * Class MonerisErrors
 * @package Moneris\Loop
 */
class MonerisErrors extends BaseMonerisErrorsLoop
{
    /**
     * You may now add your own logic
     */
}
