<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Moneris\Form;

use Moneris\Form\Base\MonerisErrorsUpdateForm as BaseMonerisErrorsUpdateForm;

/**
 * Class MonerisErrorsUpdateForm
 * @package Moneris\Form
 */
class MonerisErrorsUpdateForm extends BaseMonerisErrorsUpdateForm
{
    public function getTranslationKeys()
    {
        return array(
            "id" => "id",
            "order_id" => "order_id",
            "message" => "message",
        );
    }
}
