<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Moneris\Form;

use Moneris\Form\Base\MonerisErrorsCreateForm as BaseMonerisErrorsCreateForm;

/**
 * Class MonerisErrorsCreateForm
 * @package Moneris\Form
 */
class MonerisErrorsCreateForm extends BaseMonerisErrorsCreateForm
{
    public function getTranslationKeys()
    {
        return array(
            "order_id" => "Order id",
            "message" => "Message",
        );
    }
}
