<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Moneris\Event\Module;

use Moneris\Event\Module\Base\MonerisEvents as BaseMonerisEvents;

/**
 * Class MonerisEvents
 * @package Moneris\Event\Module
 * @author TheliaStudio
 */
class MonerisEvents extends BaseMonerisEvents
{
}
