<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Moneris\Controller\Base;

use Symfony\Component\HttpFoundation\RedirectResponse;
use Thelia\Controller\Admin\AbstractCrudController;
use Thelia\Core\Security\Resource\AdminResources;
use Thelia\Tools\URL;
use Moneris\Event\MonerisErrorsEvent;
use Moneris\Event\MonerisErrorsEvents;
use Moneris\Model\MonerisErrorsQuery;

/**
 * Class MonerisErrorsController
 * @package Moneris\Controller\Base
 * @author TheliaStudio
 */
class MonerisErrorsController extends AbstractCrudController
{
    public function __construct()
    {
        parent::__construct(
            "moneris_errors",
            "id",
            "order",
            AdminResources::MODULE,
            MonerisErrorsEvents::CREATE,
            MonerisErrorsEvents::UPDATE,
            MonerisErrorsEvents::DELETE,
            null,
            null,
            "Moneris"
        );
    }

    /**
     * Return the creation form for this object
     */
    protected function getCreationForm()
    {
        return $this->createForm("moneris_errors.create");
    }

    /**
     * Return the update form for this object
     */
    protected function getUpdateForm($data = array())
    {
        if (!is_array($data)) {
            $data = array();
        }

        return $this->createForm("moneris_errors.update", "form", $data);
    }

    /**
     * Hydrate the update form for this object, before passing it to the update template
     *
     * @param mixed $object
     */
    protected function hydrateObjectForm($object)
    {
        $data = array(
            "id" => $object->getId(),
            "order_id" => $object->getOrderId(),
            "message" => $object->getMessage(),
        );

        return $this->getUpdateForm($data);
    }

    /**
     * Creates the creation event with the provided form data
     *
     * @param mixed $formData
     * @return \Thelia\Core\Event\ActionEvent
     */
    protected function getCreationEvent($formData)
    {
        $event = new MonerisErrorsEvent();

        $event->setOrderId($formData["order_id"]);
        $event->setMessage($formData["message"]);

        return $event;
    }

    /**
     * Creates the update event with the provided form data
     *
     * @param mixed $formData
     * @return \Thelia\Core\Event\ActionEvent
     */
    protected function getUpdateEvent($formData)
    {
        $event = new MonerisErrorsEvent();

        $event->setId($formData["id"]);
        $event->setOrderId($formData["order_id"]);
        $event->setMessage($formData["message"]);

        return $event;
    }

    /**
     * Creates the delete event with the provided form data
     */
    protected function getDeleteEvent()
    {
        $event = new MonerisErrorsEvent();

        $event->setId($this->getRequest()->request->get("moneris_errors_id"));

        return $event;
    }

    /**
     * Return true if the event contains the object, e.g. the action has updated the object in the event.
     *
     * @param mixed $event
     */
    protected function eventContainsObject($event)
    {
        return null !== $this->getObjectFromEvent($event);
    }

    /**
     * Get the created object from an event.
     *
     * @param mixed $event
     */
    protected function getObjectFromEvent($event)
    {
        return $event->getMonerisErrors();
    }

    /**
     * Load an existing object from the database
     */
    protected function getExistingObject()
    {
        return MonerisErrorsQuery::create()
            ->findPk($this->getRequest()->query->get("moneris_errors_id"))
        ;
    }

    /**
     * Returns the object label form the object event (name, title, etc.)
     *
     * @param mixed $object
     */
    protected function getObjectLabel($object)
    {
        return '';
    }

    /**
     * Returns the object ID from the object
     *
     * @param mixed $object
     */
    protected function getObjectId($object)
    {
        return $object->getId();
    }

    /**
     * Render the main list template
     *
     * @param mixed $currentOrder , if any, null otherwise.
     */
    protected function renderListTemplate($currentOrder)
    {
        $this->getParser()
            ->assign("order", $currentOrder)
        ;

        return $this->render("moneris-errorss");
    }

    /**
     * Render the edition template
     */
    protected function renderEditionTemplate()
    {
        $this->getParserContext()
            ->set(
                "moneris_errors_id",
                $this->getRequest()->query->get("moneris_errors_id")
            )
        ;

        return $this->render("moneris-errors-edit");
    }

    /**
     * Must return a RedirectResponse instance
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    protected function redirectToEditionTemplate()
    {
        $id = $this->getRequest()->query->get("moneris_errors_id");

        return new RedirectResponse(
            URL::getInstance()->absoluteUrl(
                "/admin/module/Moneris/moneris_errors/edit",
                [
                    "moneris_errors_id" => $id,
                ]
            )
        );
    }

    /**
     * Must return a RedirectResponse instance
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    protected function redirectToListTemplate()
    {
        return new RedirectResponse(
            URL::getInstance()->absoluteUrl("/admin/module/Moneris/moneris_errors")
        );
    }
}
