<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Moneris\Event\Base;

use Moneris\Event\Module\MonerisEvents as ChildMonerisEvents;

/*
 * Class MonerisErrorsEvents
 * @package Moneris\Event\Base
 * @author TheliaStudio
 */
class MonerisErrorsEvents
{
    const CREATE = ChildMonerisEvents::MONERIS_ERRORS_CREATE;
    const UPDATE = ChildMonerisEvents::MONERIS_ERRORS_UPDATE;
    const DELETE = ChildMonerisEvents::MONERIS_ERRORS_DELETE;
}
