<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Moneris\Controller;

use Moneris\Controller\Base\MonerisConfigController as BaseMonerisConfigController;

/**
 * Class MonerisConfigController
 * @package Moneris\Controller
 */
class MonerisConfigController extends BaseMonerisConfigController
{
}
