<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Moneris\Controller;

use Moneris\Controller\Base\MonerisErrorsController as BaseMonerisErrorsController;

/**
 * Class MonerisErrorsController
 * @package Moneris\Controller
 */
class MonerisErrorsController extends BaseMonerisErrorsController
{
}
