<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Moneris\Action\Base;

use Moneris\Model\Map\MonerisErrorsTableMap;
use Moneris\Event\MonerisErrorsEvent;
use Moneris\Event\MonerisErrorsEvents;
use Moneris\Model\MonerisErrorsQuery;
use Moneris\Model\MonerisErrors;
use Thelia\Action\BaseAction;
use Thelia\Core\Event\ToggleVisibilityEvent;
use Thelia\Core\Event\UpdatePositionEvent;
use Propel\Runtime\Propel;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Thelia\Core\Event\TheliaEvents;
use \Thelia\Core\Event\TheliaFormEvent;

/**
 * Class MonerisErrorsAction
 * @package Moneris\Action
 * @author TheliaStudio
 */
class MonerisErrorsAction extends BaseAction implements EventSubscriberInterface
{
    public function create(MonerisErrorsEvent $event)
    {
        $this->createOrUpdate($event, new MonerisErrors());
    }

    public function update(MonerisErrorsEvent $event)
    {
        $model = $this->getMonerisErrors($event);

        $this->createOrUpdate($event, $model);
    }

    public function delete(MonerisErrorsEvent $event)
    {
        $this->getMonerisErrors($event)->delete();
    }

    protected function createOrUpdate(MonerisErrorsEvent $event, MonerisErrors $model)
    {
        $con = Propel::getConnection(MonerisErrorsTableMap::DATABASE_NAME);
        $con->beginTransaction();

        try {
            if (null !== $id = $event->getId()) {
                $model->setId($id);
            }

            if (null !== $orderId = $event->getOrderId()) {
                $model->setOrderId($orderId);
            }

            if (null !== $message = $event->getMessage()) {
                $model->setMessage($message);
            }

            $model->save($con);

            $con->commit();
        } catch (\Exception $e) {
            $con->rollback();

            throw $e;
        }

        $event->setMonerisErrors($model);
    }

    protected function getMonerisErrors(MonerisErrorsEvent $event)
    {
        $model = MonerisErrorsQuery::create()->findPk($event->getId());

        if (null === $model) {
            throw new \RuntimeException(sprintf(
                "The 'moneris_errors' id '%d' doesn't exist",
                $event->getId()
            ));
        }

        return $model;
    }

    public function beforeCreateFormBuild(TheliaFormEvent $event)
    {
    }

    public function beforeUpdateFormBuild(TheliaFormEvent $event)
    {
    }

    public function afterCreateFormBuild(TheliaFormEvent $event)
    {
    }

    public function afterUpdateFormBuild(TheliaFormEvent $event)
    {
    }

    /**
     * Returns an array of event names this subscriber wants to listen to.
     *
     * The array keys are event names and the value can be:
     *
     *  * The method name to call (priority defaults to 0)
     *  * An array composed of the method name to call and the priority
     *  * An array of arrays composed of the method names to call and respective
     *    priorities, or 0 if unset
     *
     * For instance:
     *
     *  * array('eventName' => 'methodName')
     *  * array('eventName' => array('methodName', $priority))
     *  * array('eventName' => array(array('methodName1', $priority), array('methodName2'))
     *
     * @return array The event names to listen to
     *
     * @api
     */
    public static function getSubscribedEvents()
    {
        return array(
            MonerisErrorsEvents::CREATE => array("create", 128),
            MonerisErrorsEvents::UPDATE => array("update", 128),
            MonerisErrorsEvents::DELETE => array("delete", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".moneris_errors_create" => array("beforeCreateFormBuild", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".moneris_errors_update" => array("beforeUpdateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".moneris_errors_create" => array("afterCreateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".moneris_errors_update" => array("afterUpdateFormBuild", 128),
        );
    }
}
